spring:
  cloud:
    stream:
      bindings:
        input:
#          binder: allen
          destination: stream-test
#      binders:
#        allen:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 10.41.1.140
#                port: 5672
#                username: admin
#                password: admin
